# Generated by Django 5.2.3 on 2025-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_images', models.ImageField(blank=True, default='default.jpg', upload_to='projects/%Y/%m/%d/')),
            ],
        ),
    ]
