# Generated by Django 5.2.6 on 2025-10-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Достопримечательность')),
                ('image', models.ImageField(blank=True, upload_to='attractions_images/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название дома')),
                ('images', models.ImageField(blank=True, upload_to='home_images/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('featured_images', models.ImageField(blank=True, upload_to='us_images/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Photo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='home_images/add/', verbose_name='Фото')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.home', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='Photo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='attractions_images/add/', verbose_name='Фото')),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.attractions', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'изображение ',
                'verbose_name_plural': 'изображения достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='us_images/add/', verbose_name='Фото')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.us', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
