# Generated by Django 5.2.6 on 2025-10-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='address',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
