# Generated by Django 5.2.3 on 2025-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True)),
                ('featured_images', models.ImageField(blank=True, upload_to='home/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='us',
            name='featured_images',
            field=models.ImageField(blank=True, upload_to='us1/%Y/%m/%d/'),
        ),
    ]
