# Generated by Django 5.2.6 on 2025-09-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_home_alter_us_featured_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_images', models.ImageField(blank=True, upload_to='home/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='us.attractions')),
            ],
        ),
    ]
