# Generated by Django 5.2.6 on 2025-10-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_attractions_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='attractions',
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'название дома', 'verbose_name_plural': 'названия домов'},
        ),
        migrations.RemoveField(
            model_name='home',
            name='featured_images',
        ),
        migrations.AddField(
            model_name='home',
            name='images',
            field=models.ImageField(blank=True, upload_to='home', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название дома'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='home_images/add', verbose_name='Фото')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.home', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.DeleteModel(
            name='Attractions',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
