# Generated by Django 5.2.6 on 2025-10-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_remove_gallery_attractions_alter_home_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Достопримечательность')),
                ('image', models.ImageField(blank=True, upload_to='attractions', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='us',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'О нас'},
        ),
        migrations.CreateModel(
            name='Photo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='attractions_images/add', verbose_name='Фото')),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.attractions', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
